version: '2.3'

volumes:
  etestatic:

services:
  etesync:
    container_name: etesync
    hostname: etesync
    image: victorrds/etesync:alpine
    expose:
      - 8000    
    volumes:
      - etestatic:/var/www/static:rw
    environment:
      - SERVER=uwsgi
    restart: on-failure
    network_mode: "bridge"
  nginx:
    container_name: nginx
    hostname: epoch
    image: nginx
    ports:
      - 443:443
      - 80:80
    volumes:      
      - ../examples/nginx-example.conf:/etc/nginx/conf.d/default.conf:ro      
      - etestatic:/var/www/static:ro
    links:
      - etesync
    #depends_on:
    #  - etesync
    restart: on-failure
    network_mode: "bridge"
