version: '2.3'

volumes:
  etestatic:

services:
  etesync:
    container_name: etesync
    hostname: etesync
    image:victorrds/etesync:latest
    expose:
      - 8000
    volumes:
      - etestatic:/var/www/static:rw
    environment:
      - SERVER=uwsgi
      - SUPER_USER=admin
      - SUPER_PASS=admin
    network_mode: "bridge"
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 443:443
      - 80:80
    volumes:
      - etestatic:/var/www/static:ro
      - ./nginx-example.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - etesync
    network_mode: "bridge"